### ISSUE TITLE
 Craft 4 - Express Forms saves submissions but won't send email notifications #232 

### ISSUE THREAD

**Issue by bjprodneyl** [solspace/craft-express-forms#100]
**Describe the bug or issue you're experiencing**
Running Express Forms 2.0.0-beta.2 on 

Have setup Express Forms. Submissions save, but email notifications fail. We are running the form using an email address we setup on our server via smtp, but have also tried the sendmail option but get same error
Steps to reproduce

**Steps to reproduce**

1.Submit form
2. Check email and spam folders
3. Check Express Forms log ans see this error: Email notification [express_forms_demo_notification.twig]: Email "" does not comply with addr-spec of RFC 2822. [] []

**Expected behavior**
Expect email notifications to send but not workiing
**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft CMS 4.2.3 (Pro)
- Express Forms Version: Express Forms 2.0.0-beta.2
- Express Forms Edition: Lite
- Fresh Install or Upgrade: fresh install

**Additional context**

    Craft version: Craft CMS 4.2.3 (Pro)
    PHP version: 8.1.9
    Database driver & version: MySQL 10.2.44
    Plugins & versions: Express Forms 2.0.0-beta.2

**Comment by kjmartens** [comment]
Hi @bjprodneyl,

Can you share with me what your email notification template and form (screenshot in CP form builder) looks like? I wonder if there's a syntax error or possibly an incorrect value entered. 🙂

**Comment by rydncn** [comment]
I've ran into this issue too since working on Craft 4 sites and using the Lite version of the plugin. I narrowed it down to being the From Name and From Email fields in the Email Notification Template.

I removed the following:
- {{ craft.app.systemSettings.getSettings("email").fromName }}
- {{ craft.app.systemSettings.getSettings("email").fromEmail }}

I then had to add in the From Name and From Email into the fields instead of using the settings above.

I haven't had a chance to test and see why this is happening unfortunately but I'm not sure if this is due to a Craft 4 change at some stage that has caused an issue with retrieving the email data from the settings.

If I get a chance to investigate this further I'll update this thread with any findings.

Hope this helps anyone as a workaround for now!

**Comment by kjmartens** [comment]
@rydncn This is because Craft 4 no longer allows the `systemSettings` approach. It needs to be updated to `projectConfig` instead:

```
fromName: '{{ craft.app.projectConfig.get('email.fromName') }}'
fromEmail: '{{ craft.app.projectConfig.get('email.fromEmail') }}'
```

🙂

**Comment by rydncn** [comment]
@kjmartens Ah! Thanks for the info. Will the [EmailNotification.php](https://github.com/solspace/craft-express-forms/blob/5e2556aa374785a72ede810339702bacd4a2dc27/packages/plugin/src/models/EmailNotification.php) model be updated to match that or will it be like this until the plugin no longer supports Craft 3?

**Comment by kjmartens** [comment]
@rydncn Good catch! I will update that file as well. 🙂

**Comment by thisisjamessmith** [comment]
Please can you get this updated in the docs too? https://docs.solspace.com/craft/express-forms/v1/overview/email-notifications/#submitter-2

**Comment by kjmartens** [comment]
> Please can you get this updated in the docs too? https://docs.solspace.com/craft/express-forms/v1/overview/email-notifications/#submitter-2

Sure, updating now. It was updated for the v2 docs, but v1 will include it as well. 🙂
